version: '3.1'

services:
  project_pg:
    image: postgres:16.1
    container_name: project_pg
    restart: always
    environment:
      POSTGRES_DB: projectsdb
      POSTGRES_USER: projects
      POSTGRES_PASSWORD: secret
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    